//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumingSOAPService.EmployeeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmpId {
            get {
                return this.EmpIdField;
            }
            set {
                if ((this.EmpIdField.Equals(value) != true)) {
                    this.EmpIdField = value;
                    this.RaisePropertyChanged("EmpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeServiceReference.EmployeeServiceSoap")]
    public interface EmployeeServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsumingSOAPService.EmployeeServiceReference.HelloWorldResponse HelloWorld(ConsumingSOAPService.EmployeeServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingSOAPService.EmployeeServiceReference.HelloWorldResponse> HelloWorldAsync(ConsumingSOAPService.EmployeeServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeeDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeDetails", ReplyAction="*")]
        ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsResponse GetEmployeeDetails(ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployeeDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsResponse> GetEmployeeDetailsAsync(ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name emp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployeeDetails", ReplyAction="*")]
        ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsResponse UpdateEmployeeDetails(ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployeeDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsResponse> UpdateEmployeeDetailsAsync(ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPService.EmployeeServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsumingSOAPService.EmployeeServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPService.EmployeeServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsumingSOAPService.EmployeeServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeDetails", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsRequestBody Body;
        
        public GetEmployeeDetailsRequest() {
        }
        
        public GetEmployeeDetailsRequest(ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeeDetailsRequestBody {
        
        public GetEmployeeDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeeDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeeDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsResponseBody Body;
        
        public GetEmployeeDetailsResponse() {
        }
        
        public GetEmployeeDetailsResponse(ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployeeDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumingSOAPService.EmployeeServiceReference.Employee GetEmployeeDetailsResult;
        
        public GetEmployeeDetailsResponseBody() {
        }
        
        public GetEmployeeDetailsResponseBody(ConsumingSOAPService.EmployeeServiceReference.Employee GetEmployeeDetailsResult) {
            this.GetEmployeeDetailsResult = GetEmployeeDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeDetails", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsRequestBody Body;
        
        public UpdateEmployeeDetailsRequest() {
        }
        
        public UpdateEmployeeDetailsRequest(ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumingSOAPService.EmployeeServiceReference.Employee emp;
        
        public UpdateEmployeeDetailsRequestBody() {
        }
        
        public UpdateEmployeeDetailsRequestBody(ConsumingSOAPService.EmployeeServiceReference.Employee emp) {
            this.emp = emp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsResponseBody Body;
        
        public UpdateEmployeeDetailsResponse() {
        }
        
        public UpdateEmployeeDetailsResponse(ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumingSOAPService.EmployeeServiceReference.Employee UpdateEmployeeDetailsResult;
        
        public UpdateEmployeeDetailsResponseBody() {
        }
        
        public UpdateEmployeeDetailsResponseBody(ConsumingSOAPService.EmployeeServiceReference.Employee UpdateEmployeeDetailsResult) {
            this.UpdateEmployeeDetailsResult = UpdateEmployeeDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeServiceSoapChannel : ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceSoapClient : System.ServiceModel.ClientBase<ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap>, ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap {
        
        public EmployeeServiceSoapClient() {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingSOAPService.EmployeeServiceReference.HelloWorldResponse ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap.HelloWorld(ConsumingSOAPService.EmployeeServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsumingSOAPService.EmployeeServiceReference.HelloWorldRequest inValue = new ConsumingSOAPService.EmployeeServiceReference.HelloWorldRequest();
            inValue.Body = new ConsumingSOAPService.EmployeeServiceReference.HelloWorldRequestBody();
            ConsumingSOAPService.EmployeeServiceReference.HelloWorldResponse retVal = ((ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingSOAPService.EmployeeServiceReference.HelloWorldResponse> ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap.HelloWorldAsync(ConsumingSOAPService.EmployeeServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingSOAPService.EmployeeServiceReference.HelloWorldResponse> HelloWorldAsync() {
            ConsumingSOAPService.EmployeeServiceReference.HelloWorldRequest inValue = new ConsumingSOAPService.EmployeeServiceReference.HelloWorldRequest();
            inValue.Body = new ConsumingSOAPService.EmployeeServiceReference.HelloWorldRequestBody();
            return ((ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsResponse ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap.GetEmployeeDetails(ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsRequest request) {
            return base.Channel.GetEmployeeDetails(request);
        }
        
        public ConsumingSOAPService.EmployeeServiceReference.Employee GetEmployeeDetails() {
            ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsRequest inValue = new ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsRequest();
            inValue.Body = new ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsRequestBody();
            ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsResponse retVal = ((ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap)(this)).GetEmployeeDetails(inValue);
            return retVal.Body.GetEmployeeDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsResponse> ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap.GetEmployeeDetailsAsync(ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsRequest request) {
            return base.Channel.GetEmployeeDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsResponse> GetEmployeeDetailsAsync() {
            ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsRequest inValue = new ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsRequest();
            inValue.Body = new ConsumingSOAPService.EmployeeServiceReference.GetEmployeeDetailsRequestBody();
            return ((ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap)(this)).GetEmployeeDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsResponse ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap.UpdateEmployeeDetails(ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsRequest request) {
            return base.Channel.UpdateEmployeeDetails(request);
        }
        
        public ConsumingSOAPService.EmployeeServiceReference.Employee UpdateEmployeeDetails(ConsumingSOAPService.EmployeeServiceReference.Employee emp) {
            ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsRequest inValue = new ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsRequest();
            inValue.Body = new ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsRequestBody();
            inValue.Body.emp = emp;
            ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsResponse retVal = ((ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap)(this)).UpdateEmployeeDetails(inValue);
            return retVal.Body.UpdateEmployeeDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsResponse> ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap.UpdateEmployeeDetailsAsync(ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsRequest request) {
            return base.Channel.UpdateEmployeeDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsResponse> UpdateEmployeeDetailsAsync(ConsumingSOAPService.EmployeeServiceReference.Employee emp) {
            ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsRequest inValue = new ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsRequest();
            inValue.Body = new ConsumingSOAPService.EmployeeServiceReference.UpdateEmployeeDetailsRequestBody();
            inValue.Body.emp = emp;
            return ((ConsumingSOAPService.EmployeeServiceReference.EmployeeServiceSoap)(this)).UpdateEmployeeDetailsAsync(inValue);
        }
    }
}
